### ISSUE TITLE
Restart zabbix client when userparameter changes.

### ISSUE THREAD

**Issue by tim-3bc7s8** [kemra102/puppet-zabbix#14]
Like my last comments, I'm new to puppet and still learning so if I've missed something obvious, I apologize in advance.

From what I can gather, the zabbix client will restart if the config changes. That is what this does, right?
   subscribe  => File['/etc/zabbix/zabbix_agentd.conf'],

Is there a way to give that same functionality for the userparameter changes?
Will adding...
   notify => Service["zabbix-agent"]
...to userparameter.pp inside the file block do this?

**Comment by kemra102** [comment]
Correct, change has been merged into master and update module released to the Puppet Forge.
