### ISSUE TITLE
Future of the project

### ISSUE THREAD

**Issue by stardude900** [kemra102/puppet-zabbix#16]
Will the be future updates or is this project in bug fix only mode?

**Comment by kemra102** [comment]
Hi,

This project should really be considered archived at this point in favour of more feature rich well maintained modules. Initially I made this decision as [wdijkerman/zabbix](https://forge.puppet.com/wdijkerman/zabbix) became the better module. If you want additional modules to look at it would also be worth reviewing [puppet/zabbix](https://forge.puppet.com/puppet/zabbix) as it is an approved module.
