### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by tim-3bc7s8** [kemra102/puppet-zabbix#9]
puppet agent version: 3.2.1
puppet server version: 3.7.3
OS: Scientific Linux 6.6

When running puppet agent -t on client, I get the following error message:
Error: Failed to apply catalog: Parameter enabled failed on Yumrepo[zabbix-non-supported]: Invalid value true. Valid values are absent. Valid values match /(0|1)/. at /etc/puppet/modules/zabbix/manifests/repo.pp:20

**Comment by tim-3bc7s8** [comment]
I upgraded the client and it works now.

**Comment by kemra102** [comment]
I did get  a quick chance to look at this and the yumrepo type changed how it handled booleans shortly after the release of the version of the client you were using. I'll have to look at adding some automated testing to find the issues between different version of the client to catch this type of thing.
